export type TrainingRole = "Operations Manager" | "Yoga Instructor" | "Puppy Monitor";

export type TrainingModule = {
  key: string;
  role: TrainingRole | "All Staff";
  title: string;
  duration: string;
  summary: string;
  lessons: string[];
};

export const TRAINING_MODULES: TrainingModule[] = [
  { key: "apy-standards", role: "All Staff", title: "The APY Experience", duration: "10 min", summary: "How APY combines wellness, culture and puppy joy in a calm, premium experience.", lessons: ["Wear clean, all-black yoga attire and non-slip grippy socks for event shifts.", "Greet every guest warmly, confirm their ticket and help latecomers settle quietly.", "Keep the room calm, clean and photo-ready; engage guests instead of only observing.", "Encourage guests to tag @afropuppyyoga and leave a Google review without pressuring them.", "Record incidents and important feedback before leaving, and protect confidential APY access information."] },
  { key: "safety-welfare", role: "All Staff", title: "Safety & Puppy Welfare", duration: "15 min", summary: "The APY rules that protect puppies, guests and the experience.", lessons: ["Puppy wellbeing comes before the class schedule, photos or guest requests.", "Watch for tucked tails, hiding, whining, crying, shivering, persistent panting, escape attempts or unusual fatigue.", "Remove a stressed, unwell or aggressive puppy from the class calmly and provide water, rest and breeder support.", "Never force a shy or tired puppy to interact; give puppies breaks between back-to-back classes.", "Escalate bites, falls, illness, injury or unsafe guest behaviour to Operations immediately."] },
  { key: "ops-event-day", role: "Operations Manager", title: "Operations Specialist: Event-Day Playbook", duration: "25 min", summary: "Run APY's venue, team, breeder and guest flow from setup through close.", lessons: ["Arrive 60 minutes before the first class and confirm the instructor, Puppy Monitors, breeder, puppy count and arrival plan.", "Set up mats, props, signage, water, puppy rest space and check-in; disinfect surfaces using APY-approved supplies.", "Confirm enough mats, pee pads, paper towels, sanitizer, toys, waste bags, gloves, water and cleaning products are available.", "Manage Luma check-in, late arrivals, class transitions and timing while supporting the instructor and Puppy Monitors.", "Capture approved behind-the-scenes content when appropriate without compromising puppy or guest safety.", "After the event, clean and pack the space, reconcile supplies, debrief the team and record incidents or feedback."] },
  { key: "ops-escalations", role: "Operations Manager", title: "Operations Specialist: Escalations", duration: "15 min", summary: "Apply APY's real escalation path when an event changes unexpectedly.", lessons: ["Contact Ay immediately for an instructor cancellation, breeder no-show, venue problem or major staffing gap.", "Separate an unwell or aggressive puppy and notify the breeder immediately; puppy wellbeing remains the priority.", "Document facts, names, times and actions without speculation.", "Do not independently promise refunds, credits or rescheduling; direct the request through APY support and obtain approval.", "Give the team one clear revised plan before communicating changes to guests."] },
  { key: "yoga-class-flow", role: "Yoga Instructor", title: "Yoga: Class Flow", duration: "20 min", summary: "Deliver an accessible APY class while leaving room for puppy interaction.", lessons: ["Review the room and puppy energy with Operations before guests enter.", "Give clear beginner-friendly options and never physically adjust without consent.", "Build frequent pauses for puppy interaction, photos and hydration.", "Finish on time so Puppy Monitors can reset the room safely."] },
  { key: "yoga-safety", role: "Yoga Instructor", title: "Yoga: Safe Instruction", duration: "15 min", summary: "Adapt the class to guests, puppies and the room in real time.", lessons: ["Keep movement slow and sightlines open whenever puppies are roaming.", "Stop a pose if a puppy enters an unsafe area or a guest appears uncomfortable.", "Direct animal-welfare concerns to Puppy Monitors and operational issues to Operations.", "Never diagnose injuries; pause participation and escalate."] },
  { key: "pm-onboarding", role: "Puppy Monitor", title: "Puppy Monitor: Shadowing & Shift Standards", duration: "15 min", summary: "Prepare for independent shifts through APY's hands-on onboarding process.", lessons: ["Complete two or three shadow classes before independently managing puppies and guests.", "Train across different breeds, litter sizes and guest groups rather than assuming every class behaves the same way.", "Arrive 60 minutes before the first class to set up mats, clean the studio and prepare the puppy area.", "Every class requires two assigned Puppy Monitors; coordinate responsibilities before guests arrive.", "Update availability by the APY deadline and report schedule changes as soon as possible."] },
  { key: "pm-puppy-care", role: "Puppy Monitor", title: "Puppy Monitor: Care & Rotation", duration: "20 min", summary: "Monitor puppy behaviour, rest and safe guest interaction throughout the day.", lessons: ["Count puppies at every transition and maintain water, a potty area and a quiet rest space.", "Watch for tucked tails, hiding, whining, crying, shivering, persistent panting, escape attempts, fatigue or rough handling.", "Remove and rest puppies before they become overstimulated; never force interaction with a shy or tired puppy.", "Check for stress or injury after each class and coordinate concerns with the breeder, second Puppy Monitor and Operations.", "Use water, potty breaks and puppy rotations throughout long or back-to-back sessions."] },
  { key: "pm-room-reset", role: "Puppy Monitor", title: "Puppy Monitor: Room & Guest Safety", duration: "20 min", summary: "Keep the studio sanitary while creating a warm and controlled guest experience.", lessons: ["Set up pee pads, water, toys, paper towels, waste bags, gloves and APY-approved disinfectant before guests arrive.", "Clean accidents quickly and discreetly, then restock supplies between every class.", "Demonstrate gentle puppy handling, watch interactions continuously and intervene calmly if a guest mishandles a puppy.", "Engage guests warmly, answer basic puppy questions and support safe cuddle and photo moments.", "Pack puppy supplies, sanitize used carriers or equipment and report shortages or incidents before leaving."] },
];

export function modulesForRole(role: string) {
  const normalized = role.toLowerCase().replaceAll("_", " ");
  return TRAINING_MODULES.filter((module) => module.role === "All Staff" || module.role.toLowerCase() === normalized);
}
